spring:
  application:
    name: calpick
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    root: WARN
    org:
      apache:
        catalina: ERROR
      hibernate:
        orm:
          connections:
            pooling: WARN
jwt:
  accessToken_expire_time: 86400000
  refreshToken_expire_time: 604800000
  secret: ${JWT_SECRET_KEY}

springdoc:
  show-login-endpoint: true

swagger-ui:
  url: ${SWAGGER_URL}